version: '3.8'
services:
  app:
    container_name: vue_app_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - .:/app
      - /app/node_modules
